components/theme/Dropdown.tsx
components/theme/Toast.tsx

Fixes
---
* Toast text color
* Dropdown z index

Fix toast text colors & dropdown z-index

---

components/projects/AuditLogs.tsx
components/projects/CreateProjectModal.tsx
components/settings/Tabs.tsx
components/theme/Input.tsx
components/theme/Toggle.tsx
components/theme/index.tsx
lib/audit.ts
package.json
pages/_app.tsx
pages/auth.js
pages/projects/index.tsx
pages/settings/audits.tsx
pages/settings/index.tsx
pages/settings/security.tsx
prisma/migrations/20230114015159_add_notification_and_marketing/migration.sql
prisma/schema.prisma
trpc/index.ts
trpc/routes/account.ts
yarn.lock

Account settings - allow users to update their account settings

---

lib/github.ts

This pull request is being made according to guidelines

fix: Fixing formatting issue.

---

components/theme/Nav.tsx
components/theme/index.tsx
pages/projects/[id]/members.tsx
styles/globals.css

**Note**:- This is just the UI, real feature to add, remove, and change permission still needs to be implemented.

feat: Complete UI for members tab

---

pages/projects/[id]/members.tsx

feat: further cleanup members page

---

components/home/Features.tsx
components/home/Hero.tsx

Fixes front text on the site

---

components/blog/Article.tsx
components/home/Features.tsx
components/home/Pricing.tsx
pages/blog/index.tsx
pages/changelog/index.tsx
pages/index.tsx

Not sure if `OpenSource` was intended

2 / Website text updates

---

components/members/AddMemberModal.tsx
components/projects/Projects.tsx
components/theme/Dropdown.tsx
components/theme/Input.tsx
package.json
pages/api/auth/[...nextauth].tsx
pages/api/invite/accept.ts
pages/projects/[id]/members.tsx
prisma/migrations/20230209073550_add_project_invite/migration.sql
prisma/migrations/20230209083859_add_role_to_project_invite/migration.sql
prisma/schema.prisma
trpc/index.ts
trpc/routes/members.ts
yarn.lock

Inviting new project members backend

---

components/branches/Filters.tsx
components/theme/Button.tsx
hooks/useCopyToClipBoard.ts
pages/projects/[id]/branches.tsx
tsconfig.json
yarn.lock

This feature adds ui design to the Project > Branches page

feat: Project > branches page ui design

---

components/theme/Toggle.tsx

feat: scale animation on toggle

---

components/branches/BranchPopover.tsx
components/branches/CreateBranchModal.tsx
components/projects/EnvironmentVariableEditor.tsx
components/theme/BaseInput.tsx
components/theme/BaseModal.tsx
components/theme/Nav.tsx
components/theme/Popover.tsx
components/theme/Tooltip.tsx
components/theme/index.tsx
hooks/useZodForm.tsx
package.json
pages/projects/[id]/index.tsx
trpc/index.ts
trpc/routes/branch.ts
yarn.lock

https://user-images.githubusercontent.com/22125423/219869629-df357db9-d9fc-46e0-807f-52369cc408f5.mov
Following are the features added to this PR:
[x] Made a reusable Branch Selector component
[x] Added `Tooltip` component
[x] Used `Tooltip` component while creating branch so that user knows the validation logic behind it
[x] Creating and saving a new branch
[x] WIP:  use same validation  schema on the client and server
[x] Added a custom hook named `useZodForm`

feat: new create new branch

---

components/branches/BranchPopover.tsx
styles/balloon.css

Often times we need a simple one liner tooltip, without much complication of importing component/hooks and passing props and what not. Lets go head and use balloon.css for this. I have imported the file, and removed font-family and changed bg/text colors
Reference
---
https://github.com/kazzkiq/balloon.css

feat: use balloon.css for simple one-liner tooltip

---

CONTRIBUTING.md
README.md

Adding slack community as well.

chore: add slack community as well

---

README.md

Adding Slack and Discord badges

Add slack and discord badges

---

package.json
utils/session.ts
yarn.lock

updated next-auth to use new getServerSession function

---

components/projects/EnvironmentVariableEditor.tsx
components/theme/Table/FilterMenu.tsx
components/theme/Table/Filters.tsx
components/theme/Table/SearchInput.tsx
components/theme/Table/Table.tsx
package.json
pages/projects/[id]/branches.tsx
pages/settings/index.tsx
prisma/migrations/20230222143240_add_created_by_column_to_branch_table/migration.sql
prisma/schema.prisma
trpc/routes/branch.ts
trpc/routes/projects.ts
yarn.lock

https://user-images.githubusercontent.com/22125423/221125740-1e4a726b-2909-4a83-8f2b-ceb2d4eed10e.mov

feat: table component using @tanstack/react-table

---

prisma/migrations/20230227082339_add_branch_status/migration.sql
prisma/schema.prisma

Adding optional branch status (open, closed, merged)

feat: add branch status

---

components/theme/Table/Filters.tsx
components/theme/Table/Table.tsx

This feature will delete the filter or sort pill from the filters header in the table component. 
Closes #160

feat: remove filters and sort pill when delete clicked (#160)

---

package.json
prisma/seed.ts
prisma/seeds/access.ts
prisma/seeds/projects.ts
prisma/seeds/types.ts
prisma/seeds/users.ts
tsconfig.json
yarn.lock

Write a seed file/command for quickstart

feat: write seed file and command for quickstart

---

lib/audit.ts
prisma/seed.ts
prisma/seeds/access.ts
prisma/seeds/projects.ts
prisma/seeds/types.ts
prisma/seeds/users.ts

feat: add seed for audits as well

---

prisma/seed.ts
prisma/seeds/access.ts
prisma/seeds/branches.ts
prisma/seeds/projects.ts
prisma/seeds/types.ts
prisma/seeds/users.ts

This PR will add the ability to seed branches for projects. 
Closes #168

feat: add branches seeder

---

components/pulls/CreatePullRequestModal.tsx
pages/projects/[id]/pulls.tsx

This PR contains a basic UI for creating a `Pull Request`
Closes #165

feat: basic create pull request modal (#165)

---

hooks/useCopyToClipBoard.ts
pages/projects/[id]/branches.tsx

feat: rendering protected branches table (#172)

---

components/members/AddMemberModal.tsx
components/members/MemberTabs.tsx
components/members/Table.tsx
components/theme/BaseEmptyState.tsx
hooks/useFuse.ts
models/member.ts
pages/projects/[id]/members.tsx
prisma/migrations/20230303065705_access_status/migration.sql
prisma/schema.prisma
prisma/seed.ts
prisma/seeds/inactiveUsers.ts
prisma/seeds/invites.ts
prisma/seeds/types.ts
trpc/routes/members.tsx
types/next-auth.d.ts
types/resources.ts
yarn.lock

Render active, pending and inactive members on the table and make it searchable

Render active, pending and inactive members on the table and make it searchable

---

pages/projects/[id]/branches.tsx
trpc/routes/projects.ts

feat: protect main branch and adjust UI accordingly (#175)

---

package.json
pages/projects/[id]/pulls.tsx
yarn.lock

feat: added hover call for pull request title (#182)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

This pull request updates PR, and ISSUE templates

chore: update bug, issue, pr templates

---

prisma/migrations/20230305070446_add_pull_requests/migration.sql
prisma/migrations/20230305072944_updated_pull_requests/migration.sql
prisma/schema.prisma

feat: added migration for pull request (#196)

---

prisma/seed.ts
prisma/seeds/pullRequests.ts
prisma/seeds/types.ts

feat: add seed for pull requests (#183)

---

prisma/migrations/20230306073954_add_missing_indices/migration.sql
prisma/schema.prisma

feat: add missing indices for association
Fixes
---

feat: add missing indices for association

---

.env.example
CONTRIBUTING.md
prisma/schema.prisma

It appears we dont need SHADOW_DATABASE, removing it for now.

feat: remove SHADOW_DATABASE for simplicity

---

components/TwoFactorModal.tsx
components/members/AddMemberModal.tsx
components/projects/CreateProjectModal.tsx
components/projects/EnvironmentVariableEditor.tsx
components/theme/Button.tsx
components/twoFactorForm.tsx
package.json
pages/auth/index.tsx
pages/auth/invite/[token].tsx
pages/projects/[id]/branches.tsx
pages/projects/[id]/integrations/index.tsx
pages/projects/[id]/settings/danger.tsx
pages/settings/audits.tsx
pages/settings/security.tsx
yarn.lock

Added `primary`, `secondary`, `danger` and it's outlined button variants.

feat: button variants

---

lib/openpgp.ts
package.json
prisma/schema.prisma
yarn.lock

Creates an OpenPGP library to encrypt, decrypt, revoke and generate keys

feat: create an openpgp library to encrypt, decrypt, revoke and generate keys

---

components/pulls/CreatePullRequestModal.tsx
components/pulls/DetailedPrTitle.tsx
components/pulls/EnvDiffViewer.tsx
components/pulls/PullRequestTitleHoverCard.tsx
package.json
pages/projects/[id]/branches.tsx
pages/projects/[id]/pulls/[prId]/index.tsx
pages/projects/[id]/pulls/index.tsx
trpc/index.ts
trpc/routes/pullRequest.ts
yarn.lock

`Pull Request` detail page and some simple backend stuffs.

feat: pull request detail

---

models/pullRequest.ts
package.json
prisma/migrations/20230311053615_alter_table_pull_requests_changed_pr_id_data_type/migration.sql
prisma/schema.prisma
prisma/seeds/pullRequests.ts
prisma/seeds/types.ts
trpc/routes/pullRequest.ts
tsconfig.json
yarn.lock

Generated `prId` when creating a new `Pull Request`.

feat: generate prId

---

components/theme/Table/Filters.tsx
components/theme/Table/Table.tsx
pages/projects/[id]/branches.tsx
pages/projects/[id]/pulls/index.tsx

Added props to `<Table />` component for Empty State.

feat: table component empty state

---

components/pulls/PullRequestTitleHoverCard.tsx
components/theme/Table/FilterMenu.tsx
components/theme/Table/Table.tsx
models/pullRequest.ts
pages/projects/[id]/pulls/[prId]/index.tsx
pages/projects/[id]/pulls/index.tsx

Improved `pulls` page and some issues related to it in between.

fix: loading dynamic content on pull request and small fixes

---

.env.example
components/blog/Article.tsx
components/theme/Table/FilterMenu.tsx
emails/index.ts
env/client.mjs
env/schema.mjs
env/server.mjs
lib/github.ts
lib/log.ts
lib/notion.ts
lib/redis.ts
lib/twoFactorAuth.ts
pages/api/auth/[...nextauth].tsx
pages/api/trpc/[trpc].ts
pages/blog/[slug].tsx
pages/blog/index.tsx
pages/projects/[id]/pulls/index.tsx
pages/settings/security.tsx
prisma/seed.ts
trpc/routes/members.tsx
tsconfig.json

Made environment variables type-safe

feat: made application environment variables type-safe

---

components/branches/BranchDropdown.tsx
pages/projects/[id]/index.tsx
prisma/seed.ts

Added new dropdown for branch selection

feat: branch dropdown

---

prisma/migrations/20230314132719_added_update_at_on_pull_requests/migration.sql
prisma/schema.prisma

Added `updatedAt` column to `PullRequest` table.

feat: add updatedAt column to pull requests table

---

pages/404.tsx

This feature includes the basic 404 page with subtle animation.
https://user-images.githubusercontent.com/22125423/225642903-08d70866-c2d2-4776-979c-3f323775e337.mov

feat: basic 404 page

---

.gitignore
components/projects/EncryptionSetup.tsx
pages/auth/index.tsx
prisma/seed.ts
prisma/seeds/e2eeSetup.ts
prisma/seeds/projects.ts
prisma/seeds/users.ts

Seed file to work with e2ee on dev

Seed file to work with e2ee on dev

---

apps/platform/emails/DeleteProjectNotice.tsx
apps/platform/emails/previews/DeleteProjectNotice.tsx
apps/platform/trpc/routes/projects.tsx

Project deletion email template.

feat: project deletion notice email template

---

apps/platform/trpc/routes/projects.tsx

fix: store project data to access log while creating project

---

apps/platform/components/icons/LockIcon.tsx
apps/platform/components/icons/index.ts
apps/platform/components/projects/Projects.tsx
apps/platform/components/projects/Tabs.tsx
apps/platform/emails/ProjectRestorationNotice.tsx
apps/platform/emails/previews/ProjectRestorationNotice.tsx
apps/platform/models/projects.ts
apps/platform/pages/projects/index.tsx
apps/platform/store/UserRole.ts
apps/platform/trpc/routes/projects.tsx
apps/platform/types/auditActions.ts

New project card design that addresses two factor auth and deleted project.
https://user-images.githubusercontent.com/22125423/227719353-63cd996d-8c81-4e2a-a6b9-92393d0df356.mov

feat: project restoration and project card design

---

apps/platform/components/branches/BranchDropdown.tsx
apps/platform/components/theme/Input.tsx
apps/platform/components/theme/TextareaGroup.tsx
apps/platform/hooks/useSeperateBranches.tsx
apps/platform/lib/helpers.ts
apps/platform/pages/projects/[slug]/audits.tsx
apps/platform/pages/projects/[slug]/branches.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/pages/projects/[slug]/integrations/index.tsx
apps/platform/pages/projects/[slug]/members.tsx
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/pages/projects/[slug]/pulls/index.tsx
apps/platform/pages/projects/[slug]/settings/danger.tsx
apps/platform/pages/projects/[slug]/settings/index.tsx
apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
apps/platform/prisma/migrations/20230325221520_add_protected_at_to_branch/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/prisma/seeds/branches.ts
apps/platform/prisma/seeds/types.ts
apps/platform/trpc/routes/branch.ts
apps/platform/trpc/routes/projects.tsx
apps/platform/utils/withAccessControl.ts
package.json

feat: Protected branch settings

---

apps/platform/lib/jobs/baseJob.ts
apps/platform/lib/jobs/deleteProjectJob.ts

Base Job class implementation and delete project job.

feat: base job class implementation and delete project cron job

---

apps/docs/package.json
apps/platform/components/errorboundary/Fallback.tsx
apps/platform/components/icons/integrations.tsx
apps/platform/components/theme/SlideOver.tsx
apps/platform/components/theme/index.tsx
apps/platform/package.json
apps/platform/pages/404.tsx
apps/platform/pages/500.tsx
apps/platform/pages/projects/[slug]/integrations/cli.tsx
apps/platform/pages/projects/[slug]/integrations/index.tsx

Just getting started with integration framework

feat: getting started with integrations

---

apps/platform/components/members/MemberDropDown.tsx
apps/platform/components/members/Table.tsx
apps/platform/models/member.ts
apps/platform/pages/auth/invite/[token].tsx
apps/platform/pages/projects/[slug]/branches.tsx
apps/platform/pages/projects/[slug]/members.tsx
apps/platform/prisma/migrations/20230328210359_add_invitation_token_expiration/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/prisma/seeds/invites.ts
apps/platform/prisma/seeds/types.ts
apps/platform/trpc/routes/members.tsx

Fixes #186
1. Created a `hasExpired` function to check if a project invite has expired and can be resent.
2. Modified the invite seed to generate random expiration dates for invites, some in the future and some in the past.
3. Implemented a TRPC route to delete a project invite, checking that the invite has not expired before deleting it.
4. Added an `invitationTokenExpiresAt` field in the `pendingInvite` table which allows for better check of the expiration date of an invite.
5. Implemented an expiration feature where the invitation link expires if the user has not accepted the invitation within 48 hours.
6. …

feat: Render invitation expired status and re-invite pending user, if they invitation expired

---

apps/platform/components/TwoFactorModal.tsx
apps/platform/components/twoFactorForm.tsx
apps/platform/emails/LockUserAccount.tsx
apps/platform/env/index.mjs
apps/platform/models/user.tsx
apps/platform/pages/api/auth/[...nextauth].tsx
apps/platform/pages/auth/2fa.tsx
apps/platform/pages/auth/index.tsx
apps/platform/pages/error/locked.tsx
apps/platform/pages/projects/index.tsx
apps/platform/prisma/migrations/20230331192157_create_user_lock_table_and_relation/migration.sql
apps/platform/prisma/migrations/20230401041617_remove_unused_column/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/trpc/router.ts
apps/platform/trpc/routes/twoFactor.tsx
apps/platform/types/resources.ts

Fixes #38
Tested for locking user account after too many failed two-factor authentication attempts:
1. Created a new user account.
2. Enabled two-factor authentication for the user.
3. Attempted to authenticate with the wrong two-factor code multiple times (more than the configured limit).
4. Verified that the user's account is locked and they cannot log in.
5. Verified that the user receives an email …

feat: Add user lockout for failed 2FA

---

.github/workflows/semantic-pr-title.yml

Fixes #313 
I used act for testing workflow and pipeline locally .
```
act
```
Outputs

feat: add semantic pr title workflow

---

.github/workflows/release.yml

feat: add release please github action

---

apps/platform/prisma/migrations/20230404060142_change_public_key_to_user_public_key/migration.sql
apps/platform/prisma/migrations/20230404060822_update_secrets_columns/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/prisma/seed.ts
apps/platform/prisma/seeds/e2eeSetup.ts
apps/platform/prisma/seeds/secrets.ts
apps/platform/prisma/seeds/types.ts
apps/platform/trpc/routes/keys.ts
apps/platform/utils/withAccessControl.ts

> This will help us tests branch, and PR features
- Terminal on Mac OS

feat: create seed file for secrets

---

apps/platform/components/integrations/CliSetup.tsx
apps/platform/components/projects/EncryptionSetup.tsx
apps/platform/components/projects/Tabs.tsx
apps/platform/layouts/Project.tsx
apps/platform/pages/api/auth/[...nextauth].tsx
apps/platform/pages/api/og.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/trpc/routes/members.tsx

Fixed build errors that are encountered while building the platform app using: `yarn build` command.

fix: build error

---

README.md

Fixes  #331 
I have used Markdown Preview from the VSCode. Here is the screenshot for this.
cc @dahal  @chetannn

docs: add CI status badge on README.md

---

apps/platform/components/members/Table.tsx

feat: Re-activate inactive users

---

apps/platform/components/projects/CreateProjectModal.tsx
apps/platform/components/projects/EncryptionSetup.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
apps/platform/prisma/migrations/20230405223045_fix_user_public_key_association/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/utils/withAccessControl.ts

This PR ensures that we create encryptedProjectKey, if it was not created already.
Fixes #312
- Crome on Mac OS

fix: create project keys, if it was not created already.

---

apps/platform/components/theme/Table/Table.tsx

> Hides search,filter,sort on empty state
Fixes #[342 Issue](https://github.com/envless/envless/issues/341)

fix: hides filters on empty state

---

apps/cli/src/commands/auth.ts
apps/cli/src/commands/init.ts
apps/cli/src/commands/privateKey.ts
apps/cli/src/commands/project/create.ts
apps/cli/src/commands/project/link.ts
apps/cli/src/lib/helpers.ts
apps/platform/utils/api/projects.controller.ts

Typos and other small quality of life improvements.

fix: cli cleanups

---

apps/platform/components/branches/CreateBranchModal.tsx
apps/platform/pages/projects/[slug]/index.tsx

Fixes [#Issue 364](https://github.com/envless/envless/issues/364)

feat: redirects to current branch after branch creation

---

.github/workflows/ci.yml
.prettierignore
apps/docs/package.json
yarn.lock

Downgrade nextra-theme-docs so builds work again.

chore: builds are failing because of nextra-theme-docs, downgrading it to last working version

---

apps/platform/components/members/MembersTableContainer.tsx

Fix: members table overflow
Closes #393

fix: members table overflow (#393)

---

apps/cli/package.json
apps/cli/src/commands/auth.ts
apps/cli/src/commands/init.ts
apps/cli/src/commands/project/create.ts
apps/cli/src/commands/project/index.ts
apps/cli/src/commands/project/link.ts
apps/cli/src/commands/run.ts
apps/cli/src/lib/dotEnvless.ts
apps/cli/src/lib/helpers.ts
apps/cli/src/utils/types.ts
apps/platform/pages/api/cli/v1/projects/[id]/secrets.ts
apps/platform/prisma/seeds/branches.ts
apps/platform/trpc/routes/projects.tsx
apps/platform/utils/api/projects.controller.ts
apps/platform/utils/withCliAuth.ts

* Implement CLI command to pull, decrypt, inject and run command
* Cleanup project topic help command
```sh
$ envless run -c 'echo "hello world"'
$ envless run -command 'yarn dev'
```
- Mac OS
- Chrome browser
- SDK / CLI - 0.0.4

feat: Fetch, decrypt, inject and run command with envless cli

---

package.json
yarn.lock

chore: update turbo

---

apps/platform/prisma/seeds/e2eeSetup.ts

Fixes the issue as Seed wasn't able to run properly inside the container environment taking up the resources and lead to segmentation fault.
Exec the platform envless container and try out yarn db:migrate and yarn db:seed
Screenshots
cc @chetannn

fix: SIGSEGV raise issue on seed process

---

apps/platform/utils/envParser.ts

Fix: Error handling for `YAML` file that contains duplicate keys.

fix: yaml duplicate keys error handling

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx
apps/platform/trpc/routes/secret.ts

Fix: Insert and update secrets

fix: insert secrets

---

apps/platform/components/theme/Table/Table.tsx
apps/platform/hooks/useBranches.ts
apps/platform/pages/projects/[slug]/branches.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/prisma/schema.prisma
apps/platform/trpc/routes/branch.ts

feat: Add ability to delete branches

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx

Fix: Toggle hidden value when input changed.

fix: toggle hidden value when input changed

---

apps/platform/pages/projects/[slug]/branches.tsx
apps/platform/trpc/routes/branch.ts

Fixes [#Issue 407](https://github.com/envless/envless/issues/407)

fix: delete branch based on role

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx
apps/platform/utils/envParser.ts

This PR fixes the issue with pasting key to the secret editor.

fix: pasting key only issue

---

apps/platform/components/projects/Tabs.tsx
apps/platform/components/projects/auditLogs/AuditLogTable.tsx
apps/platform/layouts/Project.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/pages/projects/[slug]/pulls/index.tsx

Project page margins are broken, this PR should fix them.

chore: fix project page margins

---

apps/platform/components/projects/EncryptionSetup.tsx
apps/platform/hooks/useSecret.ts
apps/platform/pages/api/auth/[...nextauth].tsx

Session update was not happening because of null name. This PR should fix it.

fix: an issue where session update was not happening when user's name is null

---

.env.example
apps/cli/src/commands/init.ts
apps/platform/components/auth/Session.tsx
apps/platform/emails/previews/DeleteProjectNotice.tsx
apps/platform/emails/previews/ProjectRestorationNotice.tsx
apps/platform/middleware.ts
apps/platform/pages/api/auth/[...nextauth].tsx
apps/platform/pages/auth/invite/[token].tsx
apps/platform/pages/auth/verify.tsx
apps/platform/pages/error/forbidden.tsx
apps/platform/pages/login.tsx
apps/platform/pages/projects/[slug]/members.tsx
apps/platform/pages/signup.tsx
apps/platform/trpc/routes/auth.tsx
apps/platform/trpc/routes/projects.tsx
apps/platform/utils/withAccessControl.ts
apps/www/components/home/Pricing.tsx

Prevent signup based on env variable. This feature is useful for self-host option

feat: Prevent signups based on env variable - useful for self host option.

---

apps/platform/components/members/MembersTableContainer.tsx
apps/platform/components/projects/auditLogs/AuditLogTable.tsx

fix: remove unused buttons from audit and member table

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx
apps/platform/prisma/migrations/20230426150837_create_secret_versions_table/migration.sql
apps/platform/prisma/migrations/20230428033835_add_missing_index/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/trpc/routes/secret.ts

This feature includes saving new version of secrets to `SecretVersion` table.

feat: secret versioning

---

CONTRIBUTING.md
apps/platform/lib/client.ts
apps/platform/middleware.ts
apps/platform/pages/api/auth/[...nextauth].tsx
apps/platform/trpc/routes/auth.tsx

Document docker setup for local development

chore: document docker setup on CONTRIBUTING.md

---

apps/platform/components/branches/CreateBranchModal.tsx
apps/platform/pages/_app.tsx
apps/platform/trpc/routes/branch.ts
prettier.config.js

Clone all the base branch secrets when new branch is created.

feat: clone all the base branch secrets when new branch created

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx
apps/platform/hooks/useSecret.ts
apps/platform/trpc/routes/secret.ts
apps/platform/types/auditActions.ts
apps/platform/types/index.d.ts
apps/platform/utils/envParser.ts

This feature includes the following things:

feat: delete secret

---

apps/platform/components/pulls/CreatePullRequestModal.tsx
apps/platform/components/pulls/DetailedPrTitle.tsx
apps/platform/components/pulls/EnvDiffViewer.tsx
apps/platform/components/pulls/PullRequestTitleHoverCard.tsx
apps/platform/models/pullRequest.ts
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/pages/projects/[slug]/pulls/index.tsx
apps/platform/prisma/migrations/20230504174434_missing_association/migration.sql
apps/platform/prisma/migrations/20230504191001_make_base_and_current_required/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/prisma/seed.ts
apps/platform/prisma/seeds/projects.ts
apps/platform/trpc/routes/pullRequest.ts

Rendering pull request diff between two branches

feat: render pull request diff

---

CONTRIBUTING.md

docs: Fix typo nad -> and

---

apps/platform/components/projects/auditLogs/AuditLogTable.tsx
apps/platform/pages/projects/[slug]/audits.tsx
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx

fix: avatars on audit table

---

apps/platform/components/integrations/CliSetup.tsx
apps/platform/components/pulls/DetailedPrTitle.tsx
apps/platform/components/pulls/PullRequestStatusBadge.tsx
apps/platform/components/pulls/PullRequestTitleHoverCard.tsx
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/trpc/routes/pullRequest.ts
apps/platform/types/auditActions.ts

This feature enables to delete opened pull requests.

feat: close pull request

---

apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/pages/projects/[slug]/pulls/index.tsx
apps/platform/trpc/routes/pullRequest.ts

Re-opening #449 due to conflicts

feat: re merge pull request

---

apps/platform/components/theme/Nav.tsx
apps/platform/env/index.mjs
apps/platform/next.config.mjs
apps/platform/package.json
apps/platform/pages/api/avatar/[name].tsx
apps/platform/utils/generateGradient.ts
apps/platform/utils/getAvatar.ts
yarn.lock

feat: Create avatar endpoint (#420)

---

apps/platform/.envless.yml
apps/platform/components/branches/BranchDropdown.tsx
apps/platform/components/projects/ProjectCommon.tsx
apps/platform/pages/projects/[slug]/index.tsx
apps/platform/pages/projects/[slug]/tree/[branchName].tsx
apps/platform/utils/withAccessControl.ts

feat: create new route for branches (#419)

---

apps/platform/components/branches/BranchDropdown.tsx
apps/platform/components/theme/TextareaGroup.tsx
apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
apps/platform/trpc/routes/branch.ts

feat: Prevent deletion of main branch (#462)

---

apps/cli/src/commands/project/link.ts
apps/cli/src/commands/secrets/index.ts
apps/cli/src/commands/start.ts
apps/cli/src/lib/helpers.ts
apps/platform/pages/api/cli/v1/projects/[id]/secrets.ts

Feature: List all the secrets using `envless secrets` command.

feat: cli list all the secrets

---

apps/cli/src/commands/secrets/set.ts
apps/cli/src/lib/helpers.ts
apps/cli/src/utils/types.ts
apps/platform/components/projects/ProjectCommon.tsx
apps/platform/pages/api/cli/v1/projects/[id]/secrets/index.ts
apps/platform/pages/api/cli/v1/projects/[id]/secrets/set.ts
apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
apps/platform/pages/projects/[slug]/tree/[branchName].tsx

Added freshly baked `secrets set <args> ` command.

feat: cli secrets set command

---

apps/platform/prisma/migrations/20230517093127_remove_unique_constraint_on_project_name/migration.sql
apps/platform/prisma/schema.prisma

Fixes [#Issue 476](https://github.com/envless/envless/issues/476)

chore: remove unique constraint on project name

---

apps/platform/components/projects/EnvironmentVariableEditor.tsx

fix: initial env upload and save issue

---

apps/docs/package.json
apps/docs/src/pages/community.mdx

wip - this is for test purpose

---

.github/workflows/experimental-release.yml
apps/docs/package.json
apps/docs/src/pages/community.mdx

chore: testing another changeset release

---

apps/platform/components/pulls/DetailedPrTitle.tsx

Fixes [#Issue 513](https://github.com/envless/envless/issues/513)

fix: links to branch page

---

apps/platform/pages/projects/[slug]/branches.tsx

Fixes [#Issue 512](https://github.com/envless/envless/issues/512)

fix: create pr from branch page

---

apps/platform/components/projects/auditLogs/AuditLogTable.tsx

Closes #515. 
Made audit table searchable by name, email, and action columns using fuse.js library.

feat: search name, email , action cols/audit table

---

.github/workflows/create-cli-release.yml
.github/workflows/package-and-distribute-cli.yml
.github/workflows/promote-cli.yml
.github/workflows/release-homebrew.yml
apps/cli/package.json
apps/cli/src/lib/keyStore.ts
scripts/homebrew/envless.rb
scripts/homebrew/homebrew.mjs
yarn.lock

This PR includes the package and distribution of official envless CLI to homebrew.

feat: distribute envless cli to homebrew

---

apps/platform/trpc/routes/pullRequest.ts

Ordered all the pull request by the `createdAt` in descending.

fix: order all the latest prs first

---

scripts/homebrew/homebrew.mjs

chore: check if repository empty to update homebrew file

---

apps/platform/components/pulls/EnvDiffViewer.tsx
apps/platform/components/pulls/PullRequestStatusBadge.tsx
apps/platform/hooks/useVersionedSecret.ts
apps/platform/pages/projects/[slug]/pulls/[prId]/index.tsx
apps/platform/prisma/migrations/20230617034801_add_branch_related_columns_to_secret_version_table/migration.sql
apps/platform/prisma/schema.prisma
apps/platform/trpc/routes/pullRequest.ts
apps/platform/types/index.d.ts

1. Lets say we have two branches main and my-new-feature
2. I add new secrets and update existing ones on my-new-feature branch
3. I create a PR after the change
4. I merge the PR to main.
5. When I go back to /pulls/123 route, since the main has already been updated with merged changes, i do not see the diff anymore.
6. So bare minimum thing we need to do is fix that.

feat: version secrets for pull request

---

.github/workflows/package-and-distribute-cli.yml
.github/workflows/promote-cli.yml

chore: build and distribute deb package

---

apps/platform/components/branches/BranchDropdown.tsx

1. Fixed user experience issue which prevented menu from closing on menu item click.
2. Introduced small changes into the full-size(full prop=true) and reduced-size(full prop=false) BranchDropdown component, by making gaps between selected branch label, input, and chevron smaller, and resizing.
Fixes #511 

fix: branch selector on protected branch page design and UX improvement

---

apps/platform/trpc/routes/secret.ts

Currently when updating secrets on any branch that is current in the pull request does reflect any changes in the pull request itself. This PR includes `upserting` records to `SecretVersion` table when any changes made to branch that is current to the pull request so that changes made in branch will reflect in pull request.

fix: update pr secrets when updating branch secrets for current branch
