envless/envless

- pages/projects/[id]/audits.tsx
- pages/projects/[id]/branches.tsx
- pages/projects/[id]/index.tsx
- pages/projects/[id]/members.tsx
- pages/projects/[id]/merge-requests.tsx
- pages/projects/[id]/settings.tsx
- pages/projects/index.tsx
- pages/settings/audits.tsx
- pages/settings/index.tsx
- pages/settings/security.tsx
- utils/get-server-auth-session.ts
As mentioned in the docs:
https://next-auth.js.org/configuration/nextjs
It is not recommended to use `getSession` in API routes or `getServerSideProps` as it results to extra `fetch` to an API.
> Used server side session in getServerSideProps instead of client

- pages/settings/security.tsx
- trpc/routes/twoFactor.ts
For additional security, ask users to provide 2FA OTP code before allowing them to disable 2FA
https://user-images.githubusercontent.com/3684236/219575430-0bf9016e-be89-46f0-aa93-997c215e34d1.mp4
> feat: additional security - ask users to provide OTP for one last time before they disable two factor auth

- components/theme/Button.tsx
The issue with `Button` component when  passing `width` prop has been fixed.
> fix: button full width issue

- components/theme/Table/Filters.tsx
When removing a single filter from `<Table />` component removes other applied filters as well.
> fix: removing single filter from table removes all other filters

- components/projects/CreateProjectModal.tsx
- prisma/migrations/20230311075207_add_slug_column_to_project/migration.sql
- prisma/schema.prisma
- prisma/seeds/projects.ts
- prisma/seeds/types.ts
- trpc/routes/projects.ts
This feature attempts to fix this issue #194
1. Test the functionality of the kebabCase function by calling it with different strings that include spaces, uppercase letters, and special characters, and ensure that it returns the expected kebab-case string.
2. Test the CreateProjectModal component by rendering it and simulating user interactions such as filling the form and submitting it, and ensure …
> feat: create project slug

- trpc/context.ts
Fixes # (deprecated API)
Removed `unstable_get_server_session` function imported from `next-auth` to create the `trpc` context.
> fix: remove `unstable_get_server_session` from trpc create context

- components/theme/Table/FilterMenu.tsx
- models/pullRequest.ts
- pages/projects/[id]/pulls/[prId]/index.tsx
- pages/projects/[id]/pulls/index.tsx
Prettified PR detail page url with `prId` instead of its primary key i.e `id` generated with `cuid`
Closes #218
> feat: prettify pr detail page url with prId instead of its cuid

- __tests__/e2e/example.spec.ts
- __tests__/unit/encryption.spec.ts
- components/members/AddMemberModal.tsx
- components/projects/ConfirmationModal.tsx
- components/theme/Button.tsx
- components/theme/Form.tsx
- pages/projects/[slug]/settings/danger.tsx
- pages/settings/index.tsx
- playwright.config.ts
- trpc/routes/projects.ts
- vitest.config.ts
I made the changes to the confirmation modal component. Still it's API is not stable but fine for now.
Also added a generic form component
> fix: confirmation input and generic form

- pages/500.tsx
> Adds a 500.tsx file which is served if there is error in methods like : getServerSideProps, getStaticProps, ...
Fixes #257
>  feat: custom 500 page on next server error

- apps/platform/layouts/Settings.tsx
Removed Audit logs button option on `Settings` layout to get rid of the button in `/settings` page
Fixes #285
- OS with version: Windows 11 Pro 22H2 running WSL2 Ubuntu 22.04.2
- Browser with version: Mozilla Firefox 111.0
- SDK / CLI with version: Node.js 18.15.0, Yarn 1.22.19
> Removing Audit logs button from settings page

- apps/platform/components/projects/ProjectSettings.tsx
- apps/platform/components/projects/Tabs.tsx
- apps/platform/layouts/Project.tsx
- apps/platform/models/access.tsx
- apps/platform/models/projects.ts
- apps/platform/pages/projects/[slug]/index.tsx
- apps/platform/pages/projects/[slug]/settings/danger.tsx
- apps/platform/pages/projects/[slug]/settings/index.tsx
- apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
- apps/platform/pages/projects/index.tsx
- apps/platform/trpc/routes/projects.tsx
- apps/platform/utils/helpers.ts
- apps/platform/utils/withAccessControl.ts
Refactored `project settings` pages using `withAccessControl` server-side page function.
> fix: refactor using custom server side props function

- apps/platform/trpc/routes/account.ts
- apps/platform/trpc/routes/branch.ts
- apps/platform/trpc/routes/members.tsx
- apps/platform/trpc/routes/projects.tsx
- apps/platform/types/auditActions.ts
Added typescript constants to store all the `access` types.
Closes #159
> refactor: access action types for audit log

- apps/platform/package.json
- yarn.lock
Fixes #324
Tested that the application works and there is a new `update` helper when `useSession` is called:
```ts
const { data, update } = useSession();
```
> chore: Update Next-Auth to Support Session Update in Client (#324)

- apps/platform/components/projects/EncryptionSetup.tsx
- apps/platform/pages/projects/[slug]/index.tsx
client.js?ab48:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
- MacOS, Chrome
> fix: the conflicts between useState and useEffect

- apps/platform/components/integrations/CliSetup.tsx
This commit adds a browser native confirm dialog to the CLI token rotation process. When the user clicks the "Regenerate CLI token" button, they are presented with a confirmation dialog that warns them that all previous CLI access will be revoked. The user must confirm this action before the token is rotated. This ensures that the user is aware of the consequences of rotating their token and prevents accidental token rotation.
The code has been modified to set the new token only after the user confirms the action. This ensures that the "Regenerate CLI token" button remains visible until the user confirms.
Closes #328 …
> feat: Add browser confirm for CLI token rotation

- apps/platform/components/branches/CreateBranchModal.tsx
- apps/platform/pages/projects/[slug]/branches.tsx
- apps/platform/pages/projects/[slug]/index.tsx
> fix: populate branches on new branch modal

- apps/platform/prisma/migrations/20230412162428_add_parent_id_and_version_to_secrets/migration.sql
- apps/platform/prisma/schema.prisma
Added `version` and `parentId` columns to `secrets` table.
> feat: added version related columns to secrets table

- apps/cli/src/commands/privateKey.ts
- apps/platform/components/branches/CreateBranchModal.tsx
`envless private --secure --copy` was throwing an error if `envless.key` did not exist on downloads folder.
> chore: fix edge case where --secure is throwing an errror on cli

- apps/platform/components/projects/EnvironmentVariableEditor.tsx
- apps/platform/utils/envParser.ts
This PR solves the problem of pasting all the supported file types i.e
- JSON
- Dot ENV
- YAML
Now, pasting all these content is supported.
> fix: handle paste for all the supported file types

- apps/platform/components/projects/Projects.tsx
- apps/platform/models/access.tsx
- apps/platform/pages/projects/[slug]/settings/index.tsx
- apps/platform/prisma/migrations/20230426030947_replace_settings_with_two_fa_required/migration.sql
- apps/platform/prisma/schema.prisma
- apps/platform/trpc/routes/projects.tsx
We currently have `settings` `jsonb` column on our project and this settings only had one record (enforce2FA). This PR replaces that with `twoFactorRequired : boolean` for simplicity.
> chore: replace settings column with twoFactorRequired boolean column

- apps/platform/components/projects/EnvironmentVariableEditor.tsx
- apps/platform/hooks/useSecret.ts
- apps/platform/prisma/migrations/20230430072551_add_uuid_column_to_secrets_table/migration.sql
- apps/platform/prisma/schema.prisma
- apps/platform/prisma/seeds/secrets.ts
- apps/platform/prisma/seeds/types.ts
- apps/platform/trpc/routes/secret.ts
- apps/platform/types/index.d.ts
- apps/platform/utils/envParser.ts
Used `uuid` to track newly added secrets on the client side.
- [] I have added tests that prove my fix is effective or that my feature works
> fix: use uuid on client side for secrets

- apps/platform/components/pulls/PullRequestTitleHoverCard.tsx
We were missing merge icon in the pr hover card when status of pr is hover.
> fix: added merge icon to pr hover card

- apps/cli/src/commands/secrets/get.ts
- apps/platform/components/projects/ProjectCommon.tsx
- apps/platform/pages/projects/[slug]/settings/protected-branch.tsx
- apps/platform/pages/projects/[slug]/tree/[branchName].tsx
This new command `envless secrets get <args>` gets all the secrets and filters out from the args passed.
> feat: cli secrets get command

- apps/platform/pages/settings/index.tsx
> We will implement email change and verification on next iteration. Scope of this issue is to make it a read-only (disabled) field.
Fixes #474
> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also st any relevant details for your test configuration
* OS with version:
* Browser with version:
* SDK / CLI with version:
> fix: make email field on settings page read only

- apps/platform/pages/settings/index.tsx
Email field in account settings did not allow to save it with empty value, while being disabled. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have performed a self-review of my code
> fix: empty email not allowed in account settings while disabled
